# Profile name can be whatever you like
rns-prodsql01:
  target: dev
  outputs:
    dev:
      type: sqlserver 
      driver: 'ODBC Driver 17 for SQL Server' 
      server: '172.22.74.254' 
      port: 1433             
      database: 'master'     
      schema: 'dbo'          
      user: 'extmertcan.coskun' 
      password: 'id3bGWpkLeDea4EAE4W9' 
      threads: 8
      trust_cert: True 