{{
  config(
    materialized = 'table',tags = ['fi_kpi','s4mevduat']
    )
}}

WITH RAW_DATA AS (
	SELECT 
		NONSAP
		,RBUKRS
		,RACCT
		,TXT20
		,TXT50
		,RTCUR
		,MIN(RunningAmountTotal) AS RunningTotal
		,DATE
		,ULKE
		,GRUPORANI
		,GRUP
		,SEKTOR
		,[ALTSEKTOR]
		,[SERBEST]
		,[ULKE_BANKA]
		,[BANKATANIMI]
		,[HESAP_TIPI_TANIMI]
		,[KREDIGRUBU]
		,[CONTRIBUTEGROUP]
		,[YK_SEKTOR]
		,[YK_ULKE]
		,[YK_KREDIGRUBU]
		,[KREDIKATEGORISI]
		,[YK_KREDIKISITI]
		,[KA_KREDIGRUBU]
		,[KA_KREDIKISITI]
		,[CASH_GRUP1]
		,[CASH_GRUP2]
		,[CASH_GRUP3]
		,[CASH_GRUP4] 
    FROM {{ ref('stg__fi_kpi_t_fact_s4mevduat') }}
	WHERE DATE IS NOT NULL
    GROUP BY
		NONSAP
		,RBUKRS
		,RACCT
		,TXT20
		,TXT50
		,RTCUR
		,DATE
		,ULKE
		,GRUPORANI
		,GRUP
		,SEKTOR
		,[ALTSEKTOR]
		,[SERBEST]
		,[ULKE_BANKA]
		,[BANKATANIMI]
		,[HESAP_TIPI_TANIMI]
		,[KREDIGRUBU]
		,[CONTRIBUTEGROUP]
		,[YK_SEKTOR]
		,[YK_ULKE]
		,[YK_KREDIGRUBU]
		,[KREDIKATEGORISI]
		,[YK_KREDIKISITI]
		,[KA_KREDIGRUBU]
		,[KA_KREDIKISITI]
		,[CASH_GRUP1]
		,[CASH_GRUP2]
		,[CASH_GRUP3]
		,[CASH_GRUP4]
)

,LAST_BALANCES_BEFORE_2023 AS (
	SELECT 
		MaxDate = '2022-12-31'
		,RBUKRS
		,RACCT
		,RunningTotal
		,RN = ROW_NUMBER() OVER(PARTITION BY RBUKRS, RACCT ORDER BY Date DESC)
	FROM RAW_DATA rd
	WHERE Date <= '2022-12-31'

)

,ALL_BALANCES AS (
	SELECT DATE,RBUKRS,RACCT,RunningTotal FROM RAW_DATA
		WHERE DATE > '2022-12-31'

	UNION ALL 

	SELECT MaxDate,RBUKRS,RACCT,RunningTotal FROM LAST_BALANCES_BEFORE_2023
		WHERE RN = 1
)

SELECT * FROM ALL_BALANCES

