
version: 2

models:
  - name: dm__hos_kpi_t_fact_hostpitalmaintenance
    description: Bu tablo tüm ekipmanların detayını ve ekipmanların planlanan maliyeti ve gerçekeleşen maliyetinin bulunduğu ana tablodur
    columns:
      - name: maintenance_period_code
        description: "bakım kodu bilgisini vermektedir"

      - name: planned_date
        description: "tarih bilgisini vermektedir"

      - name: operation_type
        description: "ekipmanların operasyon tipi bilgisi yer alır"

      - name: planned_cost
        description: "her bir ekipman için planlanan maliyet değeri vermektedir"

      - name: realized_cost
        description: "her bir ekipman için gerçekleşen maliyet değeri vermektedir"

      - name: plant
        description: "üretim yeri kodu bilgisini vermektedir"

      - name: plant_name
        description: "üretim yeri isim bilgisini vermektedir"

      - name: technical_unit
        description: "teknik birim kodu bilgisini vermektedir"

      - name: equipment_no
        description: "ekipman numarası bilgisini vermektedir"

      - name: equipment_description
        description: "üst ekipman bilgisini vermektedir"
        
      - name: subequipment_no
        description: "alt ekipman numarası bilgisini vermektedir"

      - name: subequipment_description
        description: "alt ekipman isim bilgisini vermektedir"

      - name: operation_description
        description: "işlem maddesi bilgisini vermektedir"

      - name: equipment_group
        description: "ekipman grup bilgisini vermektedir"

      - name: equipment_group_description
        description: "ekipman grup açıklama bilgisini vermektedir"

      - name: maintenance_period
        description: "ekipmanların bakım period bilgisini vermektedir"

      - name: maintenance_period_type
        description: "ekipmanların bakım period tipi hakkında (yıl,ay vb) bilgileri vermektedir"

      - name: order_opening_date
        description: "sipariş açılış tarih bilgisini vermektedir"

      - name: order_closing_date
        description: "sipariş kapanış tarih bilgisini vermektedir"

      - name: equipment_type
        description: "ekipman tipi bilgisini vermektedir"

      - name: responsible_unit
        description: "sorumlu birim bilgisini vermektedir"

      - name: currency_planned_cost
        description: "planlanan maliyet için para birimi bilgisini vermektedir"

      - name: currency_realized_cost
        description: "gerçekleşen maliyet için para birimi bilgisini vermektedir"

      - name: purchase_cost
        description: "satınalma maliyeti bilgisini vermektedir"
        
      - name: storage_cost
        description: "depo maliyeti bilgisini vermektedir"

      - name: labour_cost
        description: "işçilik maliyeti bilgisini vermektedir"

  - name: dm__hos_kpi_t_fact_hospitalrevenue
    description: Bu tablo üretim yerleri için gelir bilgisini vermektedir
    columns:
      - name: plant
        description: "üretim yeri kodu bilgisini vermektedir"
        
      - name: revenue
        description: "gelir bilgisini vermektedir"

      - name: currency
        description: "para birimi bilgisini vermektedir"
