
version: 2

models:
  - name: stg__hr_kpi_t_fact_daily_leaves
    description: Bu tablo günlük olarak kullanılan yıllık izin hareketlerinin dökümünü verir, Rpeople ile Coach sistemleri bu tabloda birleştirilmiştir.	Temmuz 2025 yılında yeni SF sistemi olan Rpeople geçişi ile beraber, o tarihe kadar kişilerin kullanıdğı tüm izinlerin toplamı toplu olarak atılmıştır.
      Örneğin bir personel 
        * 2024-01-06'de -1 gün
        * 2024-01-07'de -1 gün
        * 2024-01-08'de -1 gün
        * 2024-01-09'de -1 gün
        * 2024-07-17'de -1 gün
        * 2024-07-18'de -1 gün
        * 2024-07-19'de -1 gün
      izin kullandı ise, tek tek bugünler izin kullandı şeklinde değil. dip toplam olarak 2025-07-01 tarihinde -7 gün olarak atılmıştır. Bu sebeple sadece geçmiş sistemin verisi alındığında historic daily izin kullanım verisi kaybedilmektedir. Bu minvalde aşağıda yeni_sistem_scope_out cte'sinde bu atılan açılış kayıtları tespit edilerek filter out edilmiş eski sistemle unionlanarak historic veri kaybedilmeden korunmuştur.


