{{
  config(
    materialized = 'table',tags = ['hr_kpi_puantaj']
    )
}}

SELECT [rls_key]
      ,[rls_region]
      ,[rls_group]
      ,[rls_company] =
		      CASE 
            WHEN subcontractor = N'RCT GRUP İNŞAAT TAAHÜT SANAYİ VE Tİ' THEN 'RMG_TUR' 
            ELSE [rls_company] 
          END 
      ,[rls_businessarea]
      ,[sap_id]
      ,[project_name]
      ,[zztaseronno]
      ,[main_discipline]
      ,[dim_main_discipline]
      ,[sub_discipline]
      ,[collar_type]
      ,[working_date]
      ,[time]
      ,[plans]
      ,[leave_status]
      ,[productive_nonproductive]
      ,[night_day]
      ,[zzdurum]
      ,[personeltc]
      ,[zzworking_hours]
      ,[subcontractor_description]
      ,[zzovertime]
      ,[zzfield_m_hour_grs]
      ,[ronesans_description]
      ,[zzmeyer_hours]
      ,[zzhr_entry]
      ,[hr_description]
      ,[fkber]
      ,[transaction_date]
      ,[transaction_hours]
      ,[business_area]
      ,[zteamno]
      ,[company_name]
      ,[db_upload_timestamp]
      ,[group]
      ,[company]
      ,[name]
      ,[join_key]
      ,[dim_join_key]
      ,[position]
      ,[statu]
      ,[direct_indirect]
      ,[blue_white_collar]
      ,[project]
      ,[production_class]
      ,[team_code]
      ,[team_based]
      ,[transportation]
      ,[accommodation]
      ,[company_class]
      ,[sub_subcontractor]
      ,[subcontractor]
      ,[employee_group]
      ,[task_type]
      ,[location]
  FROM {{ ref('dm__hr_kpi_t_fact_subcontractorpersonnellogs_transformed') }}
  WHERE subcontractor = N'RCT GRUP İNŞAAT TAAHÜT SANAYİ VE Tİ'